"use client";

import React, { useEffect, useRef } from "react";
import { ArrowRight } from "lucide-react";
import type { AgenticAnalysisResult } from "../types";

/**
 * "Consumed by" and the traceability chain below are both derived
 * structurally from real state, not asserted:
 *   - Risk Fusion: this evidence's finding_id appears as a key in
 *     correlated_findings.evidence_mapping (guardian/evidence/correlation.py
 *     ::EvidenceCorrelationService.correlate() only populates that map from
 *     evidence it actually processed).
 *   - Patch Generation: some patch's evidence_ids includes this evidence id
 *     (guardian/agents/patch -- a patch is only grounded in evidence it cites).
 *   - Validation: a validation_result exists for a patch that cites this
 *     evidence (chained through the same patch -> evidence_ids link).
 * An evidence item consumed by none of these still shows in the table --
 * it was still generated by the deterministic scan, it just wasn't cited
 * by anything downstream in this particular run.
 */
export function EvidencePanel({
  result, focusFindingId, onViewFinding,
}: {
  result: AgenticAnalysisResult | null;
  /** Deep-link target: when set, the matching finding's chain row is
   * scrolled into view and highlighted -- see app/page.tsx's
   * viewFindingTrace. */
  focusFindingId?: string | null;
  /** Deep-link back to Security: clicking a finding's rule_id badge below
   * opens that finding's drawer there. */
  onViewFinding?: (findingId: string) => void;
}) {
  const focusRowRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (focusFindingId && focusRowRef.current) {
      focusRowRef.current.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  }, [focusFindingId]);

  const evidence = result?.deterministic_context.evidence || [];
  const findings = result?.deterministic_context.findings || [];
  const findingsById = new Map(findings.map((f) => [f.finding_id, f]));
  const evidenceMapping = result?.risk_fusion.evidence_mapping || {};
  const correlatedFindingIds = new Set(Object.keys(evidenceMapping));
  const patches = result?.remediation.patches || [];
  const validationResults = result?.validation.results || [];
  const validatedPatchIds = new Set(
    validationResults.filter((v) => v.status === "PASSED").map((v) => v.patch_id)
  );

  if (evidence.length === 0) {
    return <div className="text-[11px] font-mono text-[#5c5c68] text-center py-10">No evidence objects generated yet.</div>;
  }

  return (
    <div className="space-y-4">
      {/* Deterministic Finding -> Evidence -> Agent -> Risk -> Patch chain,
          one row per finding -- proves the agentic layer is grounded in
          real evidence rather than hallucinating. */}
      <div className="rounded-lg bg-[#0c0d11] border border-white/8 p-3">
        <div className="text-[9px] font-mono uppercase tracking-wider text-[#8e8e9a] mb-2">Evidence Traceability</div>
        <div className="space-y-1.5">
          {findings.map((f) => {
            const evIds = f.evidence_ids && f.evidence_ids.length > 0 ? f.evidence_ids : (f.evidence_id ? [f.evidence_id] : []);
            const correlated = correlatedFindingIds.has(f.finding_id);
            const findingPatches = patches.filter((p) => p.finding_id === f.finding_id);
            const validated = findingPatches.some((p) => validatedPatchIds.has(p.patch_id));
            const isFocused = !!focusFindingId && f.finding_id === focusFindingId;
            return (
              <div
                key={f.finding_id}
                ref={isFocused ? focusRowRef : undefined}
                className={`flex items-center gap-1.5 flex-wrap text-[9.5px] font-mono rounded px-1.5 py-1 -mx-1.5 transition-colors ${
                  isFocused ? "bg-violet-500/10 ring-1 ring-violet-500/40" : ""
                }`}
              >
                {onViewFinding ? (
                  <button
                    onClick={() => onViewFinding(f.finding_id)}
                    className="px-1.5 py-0.5 rounded bg-white/6 text-[#f4f4f8] font-semibold hover:bg-[#ff5400]/15 hover:text-[#ff5400] transition-colors cursor-pointer"
                    title="View this finding in Security"
                  >
                    {f.rule_id}
                  </button>
                ) : (
                  <span className="px-1.5 py-0.5 rounded bg-white/6 text-[#f4f4f8] font-semibold">{f.rule_id}</span>
                )}
                <ArrowRight className="w-2.5 h-2.5 text-[#5c5c68]" />
                <span className="px-1.5 py-0.5 rounded bg-white/6 text-[#8e8e9a]">{evIds.join(", ") || "—"}</span>
                <ArrowRight className="w-2.5 h-2.5 text-[#5c5c68]" />
                <span className="px-1.5 py-0.5 rounded bg-white/6 text-[#8e8e9a]">Security Agent</span>
                <ArrowRight className="w-2.5 h-2.5 text-[#5c5c68]" />
                <span className={`px-1.5 py-0.5 rounded ${correlated ? "bg-sky-500/12 text-sky-400" : "bg-white/6 text-[#5c5c68]"}`}>
                  {correlated ? "correlated" : "not correlated"}
                </span>
                <ArrowRight className="w-2.5 h-2.5 text-[#5c5c68]" />
                <span className={`px-1.5 py-0.5 rounded ${findingPatches.length > 0 ? "bg-[#ff5400]/12 text-[#ff5400]" : "bg-white/6 text-[#5c5c68]"}`}>
                  {findingPatches.length > 0 ? `${findingPatches.length} patch(es)` : "no patch"}
                </span>
                {findingPatches.length > 0 && (
                  <>
                    <ArrowRight className="w-2.5 h-2.5 text-[#5c5c68]" />
                    <span className={`px-1.5 py-0.5 rounded ${validated ? "bg-emerald-500/12 text-emerald-400" : "bg-white/6 text-[#5c5c68]"}`}>
                      {validated ? "validated" : "not validated"}
                    </span>
                  </>
                )}
              </div>
            );
          })}
        </div>
      </div>

      <div className="rounded-lg bg-[#0c0d11] border border-white/8 overflow-x-auto">
        <table className="w-full text-[10px] font-mono">
          <thead>
            <tr className="text-[#8e8e9a] border-b border-white/8">
              <th className="text-left px-3 py-1.5">Evidence ID</th>
              <th className="text-left px-3 py-1.5">Source (engine)</th>
              <th className="text-left px-3 py-1.5">File</th>
              <th className="text-left px-3 py-1.5">Line</th>
              <th className="text-left px-3 py-1.5">Rule</th>
              <th className="text-left px-3 py-1.5">Finding ID</th>
              <th className="text-left px-3 py-1.5">Confidence</th>
              <th className="text-left px-3 py-1.5">Consumed By</th>
            </tr>
          </thead>
          <tbody>
            {evidence.map((e) => {
              const finding = findingsById.get(e.finding_id);
              const patchesCitingThis = patches.filter((p) => (p.evidence_ids || []).includes(e.evidence_id));
              const validatedCitingThis = patchesCitingThis.some((p) => validatedPatchIds.has(p.patch_id));
              const consumers: string[] = [];
              if (e.finding_id && correlatedFindingIds.has(e.finding_id)) consumers.push("Risk Fusion");
              if (patchesCitingThis.length > 0) consumers.push("Patch Generation");
              if (validatedCitingThis) consumers.push("Validation");
              return (
                <tr key={e.evidence_id} className="border-b border-white/5 last:border-0">
                  <td className="px-3 py-1.5 text-[#f4f4f8] font-semibold">{e.evidence_id}</td>
                  <td className="px-3 py-1.5 text-[#8e8e9a]">{e.engine}</td>
                  <td className="px-3 py-1.5 text-[#8e8e9a] max-w-[180px] truncate">{e.file}</td>
                  <td className="px-3 py-1.5 text-[#8e8e9a]">{e.line}</td>
                  <td className="px-3 py-1.5 text-[#8e8e9a]">{finding?.rule_id || "—"}</td>
                  <td className="px-3 py-1.5 text-[#8e8e9a]">{e.finding_id}</td>
                  <td className="px-3 py-1.5 text-[#8e8e9a]">{finding?.confidence ?? "—"}</td>
                  <td className="px-3 py-1.5">
                    {consumers.length === 0 ? (
                      <span className="text-[#5c5c68]">—</span>
                    ) : (
                      <div className="flex flex-wrap gap-1">
                        {consumers.map((c) => (
                          <span key={c} className="px-1.5 py-0.5 rounded bg-emerald-500/12 text-emerald-400 text-[9px]">✓ {c}</span>
                        ))}
                      </div>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default EvidencePanel;
