"use client";

import React, { useEffect, useRef } from "react";
import { ArrowRight } from "lucide-react";
import type { AgenticAnalysisResult } from "../types";

/**
 * "Consumed by" and the traceability chain below are both derived
 * structurally from real state, not asserted:
 *   - Risk Fusion: this evidence's finding_id appears as a key in
 *     correlated_findings.evidence_mapping (guardian/evidence/correlation.py
 *     ::EvidenceCorrelationService.correlate() only populates that map from
 *     evidence it actually processed).
 *   - Patch Generation: some patch's evidence_ids includes this evidence id
 *     (guardian/agents/patch -- a patch is only grounded in evidence it cites).
 *   - Validation: a validation_result exists for a patch that cites this
 *     evidence (chained through the same patch -> evidence_ids link).
 * An evidence item consumed by none of these still shows in the table --
 * it was still generated by the deterministic scan, it just wasn't cited
 * by anything downstream in this particular run.
 */
export function EvidencePanel({
  result, focusFindingId, onViewFinding,
}: {
  result: AgenticAnalysisResult | null;
  focusFindingId?: string | null;
  onViewFinding?: (findingId: string) => void;
}) {
  const focusRowRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (focusFindingId && focusRowRef.current) {
      focusRowRef.current.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  }, [focusFindingId]);

  const evidence = result?.deterministic_context.evidence || [];
  const findings = result?.deterministic_context.findings || [];
  const findingsById = new Map(findings.map((f) => [f.finding_id, f]));
  const evidenceMapping = result?.risk_fusion.evidence_mapping || {};
  const correlatedFindingIds = new Set(Object.keys(evidenceMapping));
  const patches = result?.remediation.patches || [];
  const validationResults = result?.validation.results || [];
  const validatedPatchIds = new Set(
    validationResults.filter((v) => v.status === "PASSED").map((v) => v.patch_id)
  );

  if (evidence.length === 0) {
    return <div className="text-[11px] font-mono text-slate-500 text-center py-10">No evidence objects generated yet.</div>;
  }

  return (
    <div className="space-y-4">
      <div className="rounded-lg bg-white border border-[#DCE5F0] shadow-sm p-3">
        <div className="text-[9px] font-mono uppercase tracking-wider text-slate-500 mb-2">Evidence Traceability</div>
        <div className="space-y-1.5">
          {findings.map((f) => {
            const evIds = f.evidence_ids && f.evidence_ids.length > 0 ? f.evidence_ids : (f.evidence_id ? [f.evidence_id] : []);
            const correlated = correlatedFindingIds.has(f.finding_id);
            const findingPatches = patches.filter((p) => p.finding_id === f.finding_id);
            const validated = findingPatches.some((p) => validatedPatchIds.has(p.patch_id));
            const isFocused = !!focusFindingId && f.finding_id === focusFindingId;
            return (
              <div
                key={f.finding_id}
                ref={isFocused ? focusRowRef : undefined}
                className={`flex items-center gap-1.5 flex-wrap text-[9.5px] font-mono rounded px-1.5 py-1 -mx-1.5 transition-colors ${
                  isFocused ? "bg-blue-50 ring-1 ring-blue-300" : ""
                }`}
              >
                {onViewFinding ? (
                  <button
                    onClick={() => onViewFinding(f.finding_id)}
                    className="px-1.5 py-0.5 rounded bg-slate-100 text-blue-600 font-semibold hover:bg-blue-100 transition-colors cursor-pointer border border-[#DCE5F0]"
                    title="View this finding in Security"
                  >
                    {f.rule_id}
                  </button>
                ) : (
                  <span className="px-1.5 py-0.5 rounded bg-slate-100 text-[#111827] font-semibold border border-[#DCE5F0]">{f.rule_id}</span>
                )}
                <ArrowRight className="w-2.5 h-2.5 text-slate-400" />
                <span className="px-1.5 py-0.5 rounded bg-slate-100 text-slate-600 border border-[#DCE5F0]">{evIds.join(", ") || "—"}</span>
                <ArrowRight className="w-2.5 h-2.5 text-slate-400" />
                <span className="px-1.5 py-0.5 rounded bg-slate-100 text-slate-600 border border-[#DCE5F0]">Security Agent</span>
                <ArrowRight className="w-2.5 h-2.5 text-slate-400" />
                <span className={`px-1.5 py-0.5 rounded border ${correlated ? "bg-blue-50 text-blue-700 border-blue-200" : "bg-slate-100 text-slate-400 border-slate-200"}`}>
                  {correlated ? "correlated" : "not correlated"}
                </span>
                <ArrowRight className="w-2.5 h-2.5 text-slate-400" />
                <span className={`px-1.5 py-0.5 rounded border ${findingPatches.length > 0 ? "bg-amber-50 text-amber-700 border-amber-200" : "bg-slate-100 text-slate-400 border-slate-200"}`}>
                  {findingPatches.length > 0 ? `${findingPatches.length} patch(es)` : "no patch"}
                </span>
                {findingPatches.length > 0 && (
                  <>
                    <ArrowRight className="w-2.5 h-2.5 text-slate-400" />
                    <span className={`px-1.5 py-0.5 rounded border ${validated ? "bg-emerald-50 text-emerald-700 border-emerald-200" : "bg-slate-100 text-slate-400 border-slate-200"}`}>
                      {validated ? "validated" : "not validated"}
                    </span>
                  </>
                )}
              </div>
            );
          })}
        </div>
      </div>

      <div className="rounded-lg bg-white border border-[#DCE5F0] shadow-sm overflow-x-auto">
        <table className="w-full text-[10px] font-mono">
          <thead>
            <tr className="text-slate-500 border-b border-[#DCE5F0] bg-slate-50">
              <th className="text-left px-3 py-1.5 font-semibold">Evidence ID</th>
              <th className="text-left px-3 py-1.5 font-semibold">Source (engine)</th>
              <th className="text-left px-3 py-1.5 font-semibold">File</th>
              <th className="text-left px-3 py-1.5 font-semibold">Line</th>
              <th className="text-left px-3 py-1.5 font-semibold">Rule</th>
              <th className="text-left px-3 py-1.5 font-semibold">Finding ID</th>
              <th className="text-left px-3 py-1.5 font-semibold">Confidence</th>
              <th className="text-left px-3 py-1.5 font-semibold">Consumed By</th>
            </tr>
          </thead>
          <tbody>
            {evidence.map((e) => {
              const finding = findingsById.get(e.finding_id);
              const patchesCitingThis = patches.filter((p) => (p.evidence_ids || []).includes(e.evidence_id));
              const validatedCitingThis = patchesCitingThis.some((p) => validatedPatchIds.has(p.patch_id));
              const consumers: string[] = [];
              if (e.finding_id && correlatedFindingIds.has(e.finding_id)) consumers.push("Risk Fusion");
              if (patchesCitingThis.length > 0) consumers.push("Patch Generation");
              if (validatedCitingThis) consumers.push("Validation");
              return (
                <tr key={e.evidence_id} className="border-b border-slate-100 last:border-0 hover:bg-slate-50/50">
                  <td className="px-3 py-1.5 text-[#111827] font-semibold">{e.evidence_id}</td>
                  <td className="px-3 py-1.5 text-slate-600">{e.engine}</td>
                  <td className="px-3 py-1.5 text-slate-600 max-w-[180px] truncate">{e.file}</td>
                  <td className="px-3 py-1.5 text-slate-600">{e.line}</td>
                  <td className="px-3 py-1.5 text-slate-600">{finding?.rule_id || "—"}</td>
                  <td className="px-3 py-1.5 text-slate-600">{e.finding_id}</td>
                  <td className="px-3 py-1.5 text-slate-600">{finding?.confidence ?? "—"}</td>
                  <td className="px-3 py-1.5">
                    {consumers.length === 0 ? (
                      <span className="text-slate-400">—</span>
                    ) : (
                      <div className="flex flex-wrap gap-1">
                        {consumers.map((c) => (
                          <span key={c} className="px-1.5 py-0.5 rounded bg-emerald-50 text-emerald-700 border border-emerald-200 text-[9px] font-semibold">✓ {c}</span>
                        ))}
                      </div>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default EvidencePanel;
